### ISSUE TITLE
compile error with mozjpeg 3.0

### ISSUE THREAD

**Issue by tpetry** [danielgtaylor/jpeg-archive#17]
jpeg-archive works with mozjpeg ``2.1`` but not with ``3.0`` released a few days ago:

```
tpetry-macbook:jpeg-archive-2.0.1 tpetry$ make
cc -std=c99 -Wall -O3 -I/usr/local/Cellar/mozjpeg/include -c -o src/util.o src/util.c
src/util.c:128:15: error: no member named 'use_moz_defaults' in 'struct jpeg_compress_struct'
        cinfo.use_moz_defaults = TRUE;
        ~~~~~ ^
src/util.c:137:15: error: no member named 'optimize_scans' in 'struct jpeg_compress_struct'
        cinfo.optimize_scans = FALSE;
        ~~~~~ ^
2 errors generated.
make: *** [src/util.o] Error 1
```
The main problem is that homebrew has updated the mozjpeg formula to 3.0 and now you have to compile mozjpeg by your own to be able to compile jpeg-archive.

**Comment by danielgtaylor** [comment]
This is merged in now with #18.

**Comment by tpetry** [comment]
tagging a new release would be really usefull

**Comment by shinnn** [comment]
+1 for new release

**Comment by danielgtaylor** [comment]
A new release is coming soon, I just need to get everything compiled across the various operating systems and that takes a few hours of my free time.
